### ISSUE TITLE
Bug (?) - format problem in NCV table?

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#72]
There appears to be some format problem for the results for batches sequenced 171005, look at the NCV table?

**Comment by mayabrandi** [comment]
Yes. Fixed now!

**Comment by alieden** [comment]
Still the same for me?

Från: mayabrandi <notifications@github.com<mailto:notifications@github.com>>
Svara till: Clinical-Genomics/NIPT <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: måndag 9 oktober 2017 15:07
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com<mailto:NIPT@noreply.github.com>>
Kopia: Agne Lieden <agne.lieden@ki.se<mailto:agne.lieden@ki.se>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Ämne: Re: [Clinical-Genomics/NIPT] Bug (?) - format problem in NCV table? (#72)


Yes. Fixed now!

**Comment by mayabrandi** [comment]
Okej. Sry. Now okej?

**Comment by alieden** [comment]
Still the same and very slow response also. Perhaps a restart will solve it?

**Comment by mayabrandi** [comment]
Then, I don’t understand what the problem is maybe. The table looks good to me. 

Slow respons is probably because the database is getting bigger and bigger. I will look at that, but it has to be for a later release.

/M

**Comment by mayabrandi** [comment]
The issue here is that the thresholds have a fixed x-range. Ill open a separate issue for this.
