### ISSUE TITLE
Help wanted- Not possible to view NIPT batches

### ISSUE THREAD

**Issue by alieden** [Clinical-Genomics/NIPT#73]
Hi, 
 At the moment you can only get to the NIPT batches page, clicking on a batch causes a HTTP 500 (internt serverfel) error. Tested on two different computers and two different browsers (IE and Firefox).

**Comment by mayabrandi** [comment]
ill look into it right now.

**Comment by mayabrandi** [comment]
It's avalible again, but we will look more into the reason behind this.

**Comment by alieden** [comment]
Ok, thanks!

Från: mayabrandi [mailto:notifications@github.com]
Skickat: den 12 oktober 2017 17:02
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Help wanted- Not possible to view NIPT batches (#73)


It's avalible again, but we will look more into the reason behind this.

**Comment by ingkebil** [comment]
This is duplicate of #55 

It seems this is a problem with how we run the NIPT viewer. As far as I gather, this happens when a client disconnects from a request before it is finished. (see https://stackoverflow.com/questions/11866792/how-to-prevent-errno-32-broken-pipe)

We can only fix this by running the NIPT viewer behind a webserver. For now, it'll restart every second hour.

**Comment by alieden** [comment]
Thank you for looking into this. When do you think a solution for this could be in place? Since these are prenatal samples and we are really pushed by the referring units to provide results asap an up to two hour delay is a problem. Although the delay is not that significant (in my mind) I think this will cause a lot of stress in the lab. When the db is down they will not now if this temporary or if they should report it etc? Btw, we are unable to view the data at the moment:)

**Comment by alieden** [comment]
In relation to this I think it's a bit strange that we haven't had any problems in a long time (before you changed the address)? Could you explain that?

**Comment by ingkebil** [comment]
I've restarted the webserver.

**Comment by ingkebil** [comment]
I can only speculate. We are running the webserver behind a proxy now. So there are different timeout settings regarding connections. For some reason, the proxy and the webserver are not playing nice together.

In any case, I will change webserver today, which should resolve the problem.

**Comment by ingkebil** [comment]
This is the possible reason: https://stackoverflow.com/questions/12591760/flask-broken-pipe-with-requests

**Comment by alieden** [comment]
Thanks again for sorting this out.

Agne

13 okt. 2017 kl. 10:15 skrev Kenny Billiau <notifications@github.com<mailto:notifications@github.com>>:


This is the possible reason: https://stackoverflow.com/questions/12591760/flask-broken-pipe-with-requests

**Comment by ingkebil** [comment]
The NIPT viewer is now running with its own proper webserver. I've noticed the download still times out tho. Let us know if anything seems amiss!

**Comment by alieden** [comment]
Sorry, you mean that the problem wasn’t solved by the move?

Från: Kenny Billiau [mailto:notifications@github.com]
Skickat: den 13 oktober 2017 17:01
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Help wanted- Not possible to view NIPT batches (#73)


The NIPT viewer is now running with its own proper webserver. I've noticed the download still times out tho. Let us know if anything seems amiss!

**Comment by alieden** [comment]
The db is indeed showing the same error this morning. At the end of the text in the stackoverflow link you provided it's stated that the solution was "upgrading to flask 0.12" if I understand correctly. Is this a valid fix also for the problem we are having?

**Comment by ingkebil** [comment]
The issue reported in this ticket is solved by upgrading to a proper webserver. As far as I understood, the 'download' link sometimes timed out before and it still does now.

I did notice the website returns an Internal Server Error once in a while and we're investigating.

**Comment by ingkebil** [comment]
Update: the 'download db' link now works again. It still takes a really long time to generate the file (+100s), but it doesn't time out anylonger.

Please get back to us if the Internal Server Error persists.

**Comment by alieden** [comment]
Hi,

The internal server error is back this morning (worked fine yesterday afternoon).

Kr,

Agne

Från: Kenny Billiau [mailto:notifications@github.com]
Skickat: den 16 oktober 2017 14:26
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Help wanted- Not possible to view NIPT batches (#73)


Update: the 'download db' link now works again. It still takes a really long time to generate the file (+100s), but it doesn't time out anylonger.

Please get back to us if the Internal Server Error persists.

**Comment by ingkebil** [comment]
Hi Agne,

my apologies for this happening again and again.

Tihs is due to stale MySQL connections, leading to  'The MySQL server has gone away' after a long time of inactivity. This error was shielded by restarting the NIPT Viewer every second hour up till now.
I've changed the connection timeout settings now so that the website closes the connection after 5mins and hopefully reconnects after that.

wkr,
Kenny

**Comment by alieden** [comment]
Hi,

FYI, The server continues to give the same error this morning.

Kr,

Agne


Från: Kenny Billiau [mailto:notifications@github.com]
Skickat: den 17 oktober 2017 09:10
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Help wanted- Not possible to view NIPT batches (#73)


Hi Agne,

my apologies for this happening again and again.

Tihs is due to stale MySQL connections, leading to 'The MySQL server has gone away' after a long time of inactivity. This error was shielded by restarting the NIPT Viewer every second hour up till now.
I've changed the connection timeout settings now so that the website closes the connection after 5mins and hopefully reconnects after that.

wkr,
Kenny

**Comment by ingkebil** [comment]
Hi Agne,

I've restarted the server and I'll have a look.

wkr,
Kenny

**Comment by ingkebil** [comment]
Hi Agne,

this is a really hard problem to reproduce.
So, I have changed the timeout settings to the database and we will see tomorrow morning if the server throws a 50x error or not.

wkr,
Kenny

**Comment by alieden** [comment]
The same this morning.

Från: Kenny Billiau [mailto:notifications@github.com]
Skickat: den 18 oktober 2017 15:37
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Help wanted- Not possible to view NIPT batches (#73)


Hi Agne,

this is a really hard problem to reproduce.
So, I have changed the timeout settings to the database and we will see tomorrow morning if the server throws a 50x error or not.

wkr,
Kenny

**Comment by alieden** [comment]
Internal Server Error again this morning after putting in some requests.

Från: Kenny Billiau [mailto:notifications@github.com]
Skickat: den 18 oktober 2017 15:37
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Help wanted- Not possible to view NIPT batches (#73)


Hi Agne,

this is a really hard problem to reproduce.
So, I have changed the timeout settings to the database and we will see tomorrow morning if the server throws a 50x error or not.

wkr,
Kenny

**Comment by ingkebil** [comment]
Hi Agne,

I will resort to the old method of restarting the production server every second hour again. I will keep you posted on any progress,

wkr,
Kenny

**Comment by alieden** [comment]
I haven’t been able to use the viewer at all before lunch today, same error.

Is the restart something that is done manually i.e. do you want me to continue to flag this?

Från: Kenny Billiau [mailto:notifications@github.com]
Skickat: den 20 oktober 2017 09:54
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Help wanted- Not possible to view NIPT batches (#73)


Hi Agne,

I will resort to the old method of restarting the production server every second hour again. I will keep you posted on any progress,

wkr,
Kenny

**Comment by ingkebil** [comment]
The restart is done automatically every second hour. I might be able to
have a look at this tonight, bit more likely tomorrow.
Of course, keep on letting us know if things don't work!

wkr,
Kenny
--
Composed and sent on the road

**Comment by alieden** [comment]
Ok, so then the restart didn’t resolve the issue this time since the error has been the same all day I guess?

Från: Kenny Billiau [mailto:notifications@github.com]
Skickat: den 23 oktober 2017 12:25
Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com>
Kopia: Agne Lieden <Agne.Lieden@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/NIPT] Help wanted- Not possible to view NIPT batches (#73)

The restart is done automatically every second hour. I might be able to
have a look at this tonight, bit more likely tomorrow.
Of course, keep on letting us know if things don't work!

wkr,
Kenny
--
Composed and sent on the road

On 23 Oct 2017 12:02, "alieden" <notifications@github.com<mailto:notifications@github.com>> wrote:

> I haven’t been able to use the viewer at all before lunch today, same
> error.
>
> Is the restart something that is done manually i.e. do you want me to
> continue to flag this?
>
> Från: Kenny Billiau [mailto:notifications@github.com]
> Skickat: den 20 oktober 2017 09:54
> Till: Clinical-Genomics/NIPT <NIPT@noreply.github.com<mailto:NIPT@noreply.github.com>>
> Kopia: Agne Lieden <Agne.Lieden@ki.se<mailto:Agne.Lieden@ki.se>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
>
> Ämne: Re: [Clinical-Genomics/NIPT] Help wanted- Not possible to view NIPT
> batches (#73)
>
>
> Hi Agne,
>
> I will resort to the old method of restarting the production server every
> second hour again. I will keep you posted on any progress,
>
> wkr,
> Kenny
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub<https://github.com/
<https://github.com/%0b>> Clinical-Genomics/NIPT/issues/73#issuecomment-338133980>, or mute the
> thread<https://github.com/notifications/unsubscribe-
<https://github.com/notifications/unsubscribe-%0b>> auth/AVr8fPfE8u2K1NV9ewaj4We-Up75FlpBks5suFGygaJpZM4P3E3O>.
